spring.application.name=backend

server.port=8085
#spring.profiles.include=local
spring.datasource.url=jdbc:postgresql://localhost:5432/freeti
spring.config.import=optional:file:.env[.properties]
spring.datasource.username= ${db.us}
spring.datasource.password= ${db.ps}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
spring.security.user.password=very-strong-password
